language: php
group: stable
dist: xenial
os: linux

php:
    - 7.2
    - 7.3

# faster builds on new travis setup not using sudo
sudo: false

services:
    - mysql

# cache vendor dirs
cache:
    directories:
        - $HOME/.composer/cache

install:
    - travis_retry composer self-update && composer --version
    - travis_retry composer update --dev --prefer-dist --no-interaction
    # install php extensions
    - |
        if (php --version | grep -i HipHop > /dev/null); then
          echo "Skipping imagick and gmagick tests on HHVM"
        else
          pear config-set preferred_state beta
          printf "\n" | pecl install imagick
          # gmagick is not installed on travis currently
          #printf "\n" | pecl install gmagick
        fi

before_script:
    - cp .env.travis .env
    - mysql -e 'CREATE DATABASE yii2_rest_api_test;'
    - php yii migrate --interactive=0

script:
    - composer validate --strict
    - vendor/bin/codecept run
